### PR TITLE
modify to aware X-Forwarded-Proto Header

### PR DESCRIPTION
**Pull request by junpei-yoshino**
If there are reverse proxy with ssl, we should treat as ssl request.

### CODE REVIEW

**Comment by Remo** [comment]
what's the effect if `$_SERVER['HTTPS']` isn't set to `on`?

**Comment by fabian** [comment]
Instead of changing `$_SERVER['HTTPS']` I would rather include the check on [line 25](https://github.com/junpei-yoshino/concrete5/blob/df1cf274e4fbcbdfff2e1b35321694b7c92a0623/web/concrete/config/base.php#L25).

Similar to what yii does in [CHttpRequest.php](https://github.com/yiisoft/yii/blob/ee39b8511c6c821f2e8863655d92151cc4931448/framework/web/CHttpRequest.php#L576).

**Comment by Remo** [comment]
I agree with @fabian!
Any objections @junpei-yoshino?

**Comment by Remo** [comment]
I just checked symfony, they also have an option to manually set trusted proxies.
https://github.com/symfony/HttpFoundation/blob/master/Request.php#L1221-L1246

They also check a few more headers https://github.com/symfony/HttpFoundation/blob/master/Request.php#L65-L80

**Comment by junpei-yoshino** [comment]
Thanks.
I moved changes to line 25.
tomorrow, I try to check proxy ip address.

**Comment by mlocati** [comment]
What about adding also a check on the `HTTP_X_FORWARDED_SSL` header?

**Comment by Remo** [comment]
@junpei-yoshino any updates regarding the proxy ip check?

**Pull request closed without merging**
