### PR TITLE
Sort the installed package list to make it easier to work with

### PR DESCRIPTION
**Pull request by JohntheFish**
I got fed up with trawling through long and un-sorted lists of packages.

### CODE REVIEW

**Comment by Remo** [comment]
merged, but please be careful when creating pull requests. You've pushed your changes to your own master branch. If I wouldn't have merged this PR your master branch would be different from the upstream master branch which would make it harder to create PRs in the future.

Always create a new branch when you change something on a forked repo!

**Comment by JohntheFish** [comment]
Me, I am Git-ignorant.  I thought I had forked a new branch - will try and double check in the future.

**Comment by JohntheFish** [comment]
Am I now safe to delete my master branch (and then create a clean one ready for forking it next time)?

**Comment by mlocati** [comment]
I usually keep my own master branch in sync with the official one.
In order to do this, I use tortoisegit:
- I add [my clone](https://github.com/mlocati/concrete5-legacy) as a remote named "origin"
- I add [the offial repo](https://github.com/concrete5/concrete5-legacy) as a remote named "upstream"

Right before creating a pull request I fetch from upstream, rebase my local master branch so that it's the same as the one of the upstream. After that I create a new branch starting from that local branch.

TortoiseGit is a great help for that

**Comment by Remo** [comment]
@JohntheFish yes, you can delete your forked repo if there are no other open pull requests

**Comment by mlocati** [comment]
Until a few days ago, deleting a repo on GitHub caused the accepted pull request pages to be unavailable. I contacted GitHub and they fixed this. So yes, it's save to completly destroy (and re-create) your own clone

**Pull request merged**
