### PR TITLE
Fix #1996 Notice: Use of undefined constant

### LINKED ISSUE #1996: Notice: Use of undefined constant
This error is being thrown because concrete/core/libraries/localization.php has on line 72..
if (($locale == 'en_US') && (!ENABLE_TRANSLATE_LOCALE_EN_US)) {
Should it be...
if (($locale == 'en_US') && (!'ENABLE_TRANSLATE_LOCALE_EN_US')) {

### PR DESCRIPTION
**Pull request by ConcreteOwl**

### CODE REVIEW

**Comment by Remo** [comment]
shouldn't this take care of the problem?
https://github.com/concrete5/concrete5-legacy/blob/2b5a90bd609cba0002f038e80f383061af94fd24/web/concrete/config/localization.php#L36-L38

**Comment by ConcreteOwl** [comment]
It depends on when that code was introduced, the error I reported was thrown by php on the 1st February 2020, @mlocati proposed the code as per my pull request and I have been using that file with the new code since then with no errors.

**Comment by Remo** [comment]
It was added 7 years ago https://github.com/concrete5/concrete5-legacy/commit/826a4d79283c9f5eeef913e4feace5aa5d0e39cd

Can you check if that line exists in your case and gets executed? I currently can't see why this code would fail.

**Comment by ConcreteOwl** [comment]
Yes that line does exist in concrete/config/localization.php
I too cannot see why it would fail, but it did..
I am happy to close the issue and withdraw the pull request and maybe see if php complains again in the future.
I will restore my version of concrete/core/libraries/localization.php to its prior state and see what occurs.

**Pull request closed without merging**
