### PR TITLE
Avoid error on exporting file attribute

### PR DESCRIPTION
**Pull request by hissy**
Check if the value is a File object

### CODE REVIEW

**Comment by Remo** [comment]
did you test what happens when you delete a file in the file explorer? It happened to me that the fID was still in the database which has the effect that we had a valid object, but `isError()` was true. I often check for `$file instanceof File && !$file->isError()`

**Comment by hissy** [comment]
I'm trying to export content with Sample Content Generator add-on at current github version, but still I can't. I'd like to return to this issue after I can export content xml.

**Comment by Remo** [comment]
this problem?

image

**Comment by hissy** [comment]
Yes.

**Comment by Remo** [comment]
I think we need to set the controller, not sure how though..

**Comment by Remo** [comment]
it still doesn't work, but don't we have to pass the view name into the render method?

export method in Page class
```php
		// this is brutal but we need to do it because otherwise duplicated pages
		// that haven't yet been visited in a browser won't properly export their contents
		// because they don't have area records yet.
        $v = View::getInstance();
        $v->disableEditing();
        $v->disableLinks();
        $v->enablePreview();
        $fileName = $this->getCollectionFilename();
        ob_start();
        $v->render($fileName ? $fileName : $this);
        ob_end_clean();
```

**Comment by Remo** [comment]
in the process of trying to set the global variable `$c` I started to ask myself if we really want to export those single pages. When migrating content over to 5.7 this could cause some problems, couldn't it?

**Comment by Remo** [comment]
@aembler do we really want to export dashboard pages when migrating content over to 5.7?

**Comment by Mnkras** [comment]
Isn't there an in internal flag for stuff that is part of the core?

**Comment by Remo** [comment]
top level single pages get root=true, but I'm not aware of anything that would mark the core stuff as internal.

**Pull request closed without merging**
