### PR TITLE
URL params added to redirect URL after login

### PR DESCRIPTION
**Pull request by glukasik**
This pull request is solving:
http://www.concrete5.org/developers/bugs/5-6-3-3/redirects-after-login-with-get-properties/

I checked it and it is working for my c5 instance, however deeper review is highly recommended.

Best regards,
Grzegorz

### CODE REVIEW

**Comment by Remo** [comment]
wouldn't that open various security issues? I can easily add a delete to a file and send an admin a mail, if he's logged in, the file would be deleted without any confirmation. I think we would have to add a token to secure those links

**Comment by glukasik** [comment]
All dashboard tools? That's a lot of work.
Maybe restricting it to front-end tools or showing a popup after login, like: "You tried to visit this URL. Redirect? (Yes/No)", would do the job?
I am very motivated to have it operational, though I am not advanced core dev.

**Comment by Remo** [comment]
I don't think it's that much work, you would only have to add a token in the login form and then validate that token before you redirect. This way no one could create direct links to controller actions.

Another step in the process would do the trick too I guess, but if it isn't necessary..

**Comment by glukasik** [comment]
Remo, can you guide me where should I store this token? A Config? In a dedicated db table?
How should I generate the token? Simple md5 hash based on some var is enough?

**Comment by mlocati** [comment]
What about enconding/decoding it with the session id?

**Comment by Remo** [comment]
@mlocati Encoding would work too, I just feel that tokens are more concrete5 like..
@glukasik  Here's an example on how to  use the validation helper to create one time tokens: http://www.concrete5.org/community/forums/customizing_c5/token-validation-helper/

**Comment by glukasik** [comment]
Thanks guys for your tips! Unfortunately, I am busy now but early next week I should be back with a solution.

**Comment by glukasik** [comment]
Hello @Remo @mlocati 
I have updated the feature with a token checking.
Though, I found one issue with the feature - after submitting bad credentials "attr" is missing.
Please wait for a fix.

**Comment by glukasik** [comment]
Dear All,
With the last commit I solved the issue with disappearing attribute values when incorrect login details are provided.
Ready to merge!

**Comment by Remo** [comment]
this doesn't seem to work for me. The attr input field is always empty, but `$parameters` in page_forbidden.php contains two array items. Any ideas what I'm doing wrong?

Also, why do you process $_REQUEST, can't see the reason for this:
https://github.com/concrete5/concrete5-legacy/pull/1898/files#diff-e0ec790ae6cc8167b55d1fb32db77543R234

**Pull request closed without merging**
