### PR TITLE
Prevent possible XSS

### PR DESCRIPTION
**Pull request by okhayat**
URL Encode value since it's used in URL

### CODE REVIEW

**Comment by Remo** [comment]
@okhayat Any reason not to use `Loader::helper('text')->sanitize(..)`? From what I've read it's not recommended to use `urlencode` to protect against XSS

**Comment by okhayat** [comment]
Not really. I just thought it would be ok. If it's better, I'll just update the code.

thanks,

**Comment by Remo** [comment]
not sure myself!

**Comment by Remo** [comment]
this recommends `htmlspecialchars`  http://stackoverflow.com/a/5037413/5027773
sanitize only calls `strip_tags`, I don't think that's good enough either!

**Comment by Remo** [comment]
I think `h(..)` should be good:
https://github.com/concrete5/concrete5-legacy/pull/1801/files
https://github.com/concrete5/concrete5-legacy/pull/1101/files

**Comment by okhayat** [comment]
Updated. Thanks for the recommendation.
Hope this helps.

**Comment by Remo** [comment]
thanks

**Pull request merged**
