### PR TITLE
Make concrete5 Legacy compatible with PHP from 5.3.2 to 7.2.0

### PR DESCRIPTION
**Pull request by mlocati**
- New concrete5 version: 5.6.4.0
- Fix ADODb
  - upgrade ADODb from 5.18a to 5.20.9
  - patch ADODb to support mysqli and mysqlt
  - fix quoting empty strings
- Fix MySQL issues:
  - set a less strict MySQL mode, to grant compatibility with queries that will break with the flags ONLY_FULL_GROUP_BY, NO_ENGINE_SUBSTITUTION, STRICT_TRANS_TABLES, STRICT_ALL_TABLES
  - use NULL instead of 0000-00-00 00:00:00 for empty dates
- Fix LSP issues:
  - rename Collection::add to Collection::addCollection (use magic methods for backward compatibility)
  - rename from Collection::duplicate to Collection::duplicateCollection (use magic methods for backward compatibility)
  - rename AttributeKey::getList to AttributeKey::getCategoryList (use magic methods for backward compatibility)
  - rename Page::add to Page::addChildPage (use magic methods for backward compatibility)
  - rename SinglePage::add to SinglePage::createSinglePage (use magic methods for backward compatibility)
  - rename WorkflowProgress::add to WorkflowProgress::addWorkflowProgress (use magic methods for backward compatibility)
  - rename Concrete5_Model_WorkflowRequest::trigger to Concrete5_Model_WorkflowRequest::triggerWorkflowRequest (use magic methods for backward compatibility)
  - rename AttributeKey::add to AttributeKey::addAttributeKey
  - let Concrete5_Model_PermissionAccess::save() accept an argument
  - make UserAttributeKey::load compatible with AttributeKey::load
  - make AttributeKey::export compatible with child classes signature
  - make AttributeType::getList compatible with child classes
  - make all the Controller::setupAndRun methods with the same signature
  - make AttributeTypeController::post method compatible with the parent one
  - make AttributeTypeController::request method compatible with the parent one
  - make AttributeTypeController::saveKey method compatible with the child ones
  - make AttributeTypeController::duplicateKey method compatible with the child ones
  - make all the exportValue methods of attribute types compatible with the exportValue method of AttributeTypeController
  - make AttributeTypeController::searchKeywords compatible with child classes
  - make AttributeType_Address::validateKey method compatible with the parent one
  - make BlockController::get compatible with Controller::get
  - make Page::getByID compatible with the child class methods
  - make all the PermissionAssignment::setPermissionObject compatible
  - make ItemList::getPage method compatible with the one of its child classes
  - make MarketplaceRemoteItem::sortBy compatible with the one of its parent class
  - make GlobalArea compatible with Area (Area::display now doesn't require a page instance as first parameter: if it's not specified we'll use the current page).
  - make AttributeTypeView::action() compatible with View::action()
  - make HtmlV2Helper::css and HtmlV2Helper::javascript compatible with base class
  - make UpdateArchive::install() compatible with Concrete5_Library_Archive::install()
  - make Concrete5_Model_GroupSetList::get compatible with parent class method
- Fix static methods calls:
  - View::element
  - Concrete5_Library_Content_Importer::setupPageNodeOrder
  - Concrete5_Model_AttributeKey::reindex
  - Page::rescanCollectionPath
  - UserAttributeKey::sortListByDisplayOrder
  - Collection::reindexPendingPages now requires the index to be operated on with PHP 7+.
  - rename File::getDownloadStatistics to File::getFileDownloadStatistics and File::getGlobalDownloadStatistics (use magic methods for backward compatibility)
  - add new method Survey::prepareChart to prepare the surveys chart data
- Fix reserved keywords for PHP 7.2
  - rename the Object class to ConcreteObject (for PHP versions prior to 7.2, Object is defined as an alias of ConcreteObject, for PHP 7.2+ there's no class named Object)
- Avoid warnings shown because of PHP 7.2 changes
  - don't use undefined constants to represent strings
  - don't access undefined constants
  - call count() only for countable variables
- Fix bugs
  - fix count on not array in Zend_Db_Table_Abstract::find()
  - fix query in Page::getPagePaths
  - fix checking workflow in dashboard/composer/write single page
  - fix checking workflow in dashboard/blocks/stacks single page
  - fix checking workflow in page_controls_menu_js tool
  - fix bug in formatTime method of date helper
  - fix error checking in dashboard/users/groups single page

### CODE REVIEW

**Comment by a3020** [comment]
I've tested this on an existing installation. Haven't found an issue so far, so this looks really promising. 🎉
 Make sure though that you've enabled the `mysqli` extension in php.ini.

**Comment by JeRoNZ** [comment]
I'm getting an exception on installation:

Unable to install database: The used table type doesn't support FULLTEXT indexes

when running a clean install with PHP 7.0.21

I made a fresh clone of https://github.com/concrete5/concrete5-legacy and then applied the pull with  git fetch origin pull/1955/head:localdev  and then switched to localdev - I assume that's the right way to test this out?

My default table type is InnoDB which of course does not support full text indexes. I guessed this is probably the PageSearchIndex table that's causing the problem. I removed the four  <FULLTEXT /> lines from web/concrete/config/db.xml and tried again (dropped database) and the install worked. Wow!

It seems the lines in web/concrete/config/db.xml
<opt platform="MYSQL">ENGINE=MYISAM</opt>
<opt platform="MYSQLT">ENGINE=MYISAM</opt>
<opt platform="MYSQLI">ENGINE=MYISAM</opt>
are being ignored somehow?

Also web/concrete/helpers/concrete/upgrade/db/version_5406.xml refers to MYSQL only. Adding in MYSQLI and MYSQLT to the PageSearchIndex element didn't fix it though.

**Comment by Remo** [comment]
@JeRoNZ fulltext is available in InnoDB since MySQL 5.6.4, what version are you using?

**Comment by JeRoNZ** [comment]
@Remo 5.5.54-0ubuntu0.12.04.1-log.

That probably doesn't explain why the ENGINE=MYISAM directive is being ignored though.

**Comment by Remo** [comment]
@JeRoNZ correct, but it explain the error. You might want to update your server though ;-)

**Comment by mlocati** [comment]
@JeRoNZ You are right: I forgot to fix the mysqli ADOdb provider: https://github.com/concrete5/concrete5-legacy/pull/1955/commits/b3e3a0a93ce5065ffcf627ed2f8296550451f163 should fix the issue (by forcing the MyISAM engine on tables that specify it)

**Comment by JeRoNZ** [comment]
@Remo , yes, it's an old dev box which I have to use for legacy stuff. I also have a Centos 7 server which is in support until 2024, which is running 5.5.52-MariaDB which presumably has the same issue. I guess a few other folks will too.

@mlocati yes that has definitely fixed it - clean install worked OK. Thanks.

**Comment by mlocati** [comment]
@JeRoNZ Thanks for checking!

**Comment by aembler** [comment]
This is awesome. Thanks @mlocati

**Comment by JohntheFish** [comment]
with 8.3.1 now released, can we have this officially released for the 5.6 legacy branch?

**Comment by JeRoNZ** [comment]
+1 for an official release. Happy to do any testing of that would help.

**Comment by mlocati** [comment]
@JeRoNZ you can already test what can be the new 5.6.4.0 version by downloading it from [GitHub](https://github.com/concrete5/concrete5-legacy/archive/master.zip) and posting here your feedback.

**Comment by JeRoNZ** [comment]
@mlocati - yes, I've done that. I've upgraded a couple of sites, switched to PHP7 and so far the wheels are still rolling :) My focus was more on whether anything specific needed a shakedown.

**Comment by hissy** [comment]
👍 for the official release

**Comment by JeRoNZ** [comment]
I have about a dozen sites running on PHP 7 - seems to be working just fine for me so far.

**Comment by JohntheFish** [comment]
I have had no core issues with this. 

I had some problems with addons such as eCommerce (re-ordering parameters in extending classes) and with my own Magic Data (being economical when extending classes by leaving unused default parameters off the end of declarations).

Who has run downward compatibility tests of this php7 compatible core on older versions of php and MySQL? What do we know about downward compatibility? What is the lowest version of php this will run on?

**Comment by mlocati** [comment]
@JohntheFish does the errors you have in eCommerce and Magic Data are caused by the core? Or the problems are in those packages?

I shouldn't have added any backward incompatible changes, so everything should work for PHP 5.x
For PHP 7.x, currently concrete5 5.6.4.0 is running on some (many?) production machines, and we have had just a couple of issues (that have already been fixed - see the [commits](https://github.com/concrete5/concrete5-legacy/commits/master) added after this PR was merged).

About the mimimum PHP version: as stated in the pull request title, it is 5.3.2 (previously it was 5.2.4).

**Comment by Remo** [comment]
@JohntheFish we are updating all our 5.6.x sites to 5.6.4 on an old server and when PHP dies, we'll switch the server to PHP 7. So far no issues with concrete5 5.6.4 on older PHP versions. I've seen a lot of errors in marketplace add-ons, but none in the core and we've updated quite a lot of sites.

**Comment by JohntheFish** [comment]
The problems in eCommerce and in Magic data are problems inside the addon packages not following the rules for interface specification required by php7. To date, I have found no problems with the pending 5.6.4 core.

**Comment by JohntheFish** [comment]
Seems I wan't getting notifications from this.

**Comment by mlocati** [comment]
@JohntheFish Thanks for the feedback

**Comment by JohntheFish** [comment]
Spent a few hours this afternoon making sure all my 5.6 addons are php7 compatible and updating my c5magic.co.uk site to c5.6.4 and php7. All working nicely and my impression is noticeably faster (but that could just be my wishful thinking).

**Comment by Remo** [comment]
@JohntheFish concrete5.6 sites running with php 7 are definitely faster, I was able to measure a difference of around 30% on average.

**Comment by JohntheFish** [comment]
So I am not just imagining it :-)
Need to get this officially released.

**Comment by JeRoNZ** [comment]
It certainly is faster - noticeably so. For my money it's not really about speed, it's about ensuring that 5.6 sites can still be run on supported Linux distributions. For example Ubuntu 16.04 ships with PHP 7, and I would assume that the forthcoming 18.04 will be 7.1 or 7.2. 14.04, the last LTS version to use PHP5 has a little over a year to live until it is unsupported. PHP 5.6 itself is officially unsupported in 9 months (http://php.net/supported-versions.php) The writing's on the wall.

**Comment by JohntheFish** [comment]
Managed to get eCommerce working with this. Details posted on the forums
http://www.concrete5.org/community/forums/legacy-version-5-6-x/hacking-core-ecommerce-for-php7-and-c5.6.4/#922588

**Comment by hissy** [comment]
Let's release 5.6.4

**Comment by c5enlil** [comment]
I revisited the user profile updates recently and found a few issues.  Been working between a live and test site to fix them.  Lets not let that slip through!  I'll update further this evening in regards...

**Comment by Jaska** [comment]
+1 for this to be officially released

**Pull request merged**
