### PR TITLE
Ensure maps blocks have a unique identity

### PR DESCRIPTION
**Pull request by JohntheFish**
I was having issues with maps blocks not having a unique id. I started by using proxy block id's, but that continued to give duplicate id's if a map was in a stack pulled more than once.

This solution just makes sure the id's really are unique. It could still fail if the view of a stack is cached and used in more than one place on a page.

A better solution would be a complete refactoring of the way maps blocks create and interact with their JavaScript to avoid dependence on a block ID.

### CODE REVIEW

**Comment by Remo** [comment]
do we really need the block identifier as well as the random string? Feels a bit over-engineered to me. Also, aren't internal methods like that written using camelCase instead of snake_case?

**Comment by JohntheFish** [comment]
The 5.7 version of this fix
https://github.com/concrete5/concrete5-5.7.0/pull/2253/files

Ended up with creating an identifier using
    Core::make('helper/validation/identifier')->getString(18)

I haven't looked to see if the 5.6 validation helper is capable of doing the same.

**Comment by Remo** [comment]
thanks, that looks better to me. Any chance you can update this PR?

**Comment by JohntheFish** [comment]
Changed it to create the identifier using
Loader::helper('validation/identifier')->getString(18)

**Comment by Remo** [comment]
@JohntheFish I wanted to merge this, but I'm a bit confused. You've modified `web/concrete/blocks/google_map/controller.php` while I would have thought that we should modify `web/concrete/core/controllers/blocks/google_map.php`.

Am I missing something?

**Comment by JohntheFish** [comment]
I think you are right. I have never managed to get gihub integrated with my dev system, so copy & paste these little changes. So what is/was the file that I updated by mistake?

**Comment by JohntheFish** [comment]
What's the best way to resolve this - open another pull and start fresh and clean?
Is there any deadline for 5.6.3.4?

**Comment by Remo** [comment]
well, you've made those changes in your master branch. That's something you should always avoid as you'll run into merging problems sooner or later. Might even be easier to delete the complete fork if you don't have any other open pull requests..

I don't there there's a deadline of any kind. There are just some bugs related to the image block and the thumbnail functionality which I think should be released, beside that we don't have much that must be released soon.

**Comment by JohntheFish** [comment]
When I looked closer, I realised that my changes were based on the wrong version. Please just do whatever is necessary to delete this pull and I will re-work it properly.

**Comment by JohntheFish** [comment]
After experimenting I don't think the issue of copied blocks can be solved with a quick change within the way the map block is rendered in 5.6.3.3. To make this work the way the javascript identifies the block needs to be redesigned to not use any #id.

**Comment by mlocati** [comment]
What about a static controller variable that gets incremented for each view?

**Comment by JohntheFish** [comment]
If some copies of a block are delivered from cached views, while others are delivered directly, that could still result in duplicates. Its not something I tried here, but it is something I have tried for such situations in the past.

I suspect you may have the opposite problem with the 5.7 maps block if you try to incorporate the movement of script into the footer via the controller on_page_view.

**Pull request closed without merging**
