### PR TITLE
Avatars now editable with Jcrop-Plugin

### PR DESCRIPTION
**Pull request by krellsebastian**
I've replaced the flash-Plugin to edit the avatar with the JQuery-Plugin Jcrop. Needed resolution for avatars is checked and also a preview in the regular avatar-field is provided.

### CODE REVIEW

**Comment by c5enlil** [comment]
Brilliant work here!  Dropped the files in their respective top level folders, loaded the css and javascript with a custom block on the avatar page and we're uploading profile pics from mobile!  Would love to see this part of the core.  Well worth not having webcam access!

**Comment by Remo** [comment]
@c5enlil did you test this properly? Also be careful if you just overwrote every file, there's a merge conflict in `web/concrete/single_pages/profile/avatar.php`, that we have to fix before I could merge this.

**Comment by c5enlil** [comment]
c5 5.6.3.5
php 5.6.3.6

All top level...
/controllers/profile/avatar.php
/single_pages/profile/avatar.php
/css/ccm-profile.css
/css/jquery.jcrop.css
/js/jquery.jcrop.js

was having issue getting js/css loaded so I called it from a custom header/footer block on the Avatar page and it's working!  Minus the image file......

What exactly is the pending issue?

**Comment by Remo** [comment]
* I can't merge it because of the conflict, avatar.php was changed after this PR was created
* This line we have to remove, but that's the easiest thing https://github.com/concrete5/concrete5-legacy/pull/1767#discussion_r19007868
* We might want to take care of this https://github.com/concrete5/concrete5-legacy/pull/1767#issuecomment-59483951

**Comment by c5enlil** [comment]
Fixed those lines and the t function.  Smooth sailing in Greek Yogurt!

**Comment by Remo** [comment]
any chance you could push them as a pull request?

**Comment by Remo** [comment]
We didn't delete the members page, we only delete it if public profiles are disabled, otherwise we might expose information the site owner isn't aware is public. Thanks for the PR

**Pull request closed without merging**
