### PR TITLE
Php7 fixes

### PR DESCRIPTION
**Pull request by Remo**
replaces #1917

use at your own risk! Those changes aren't made the proper way, this is merely a preview and not recommended for production! See comments by Korvin over here https://github.com/concrete5/concrete5-legacy/pull/1917#issuecomment-155906027
- [x] Fix https://github.com/concrete5/concrete5-legacy/pull/1564/files#r44568992
- [ ] Fix warnings the proper way

### CODE REVIEW

**Comment by Remo** [comment]
I had a quick look at what would be required to keep warnings on. Right at the first page I see 4 warnings:

```
Warning: Declaration of Concrete5_Model_Page::add(CollectionType $ct, $data) should be compatible with Concrete5_Model_Collection::add($data) 
Warning: Declaration of Concrete5_Model_Page::duplicate($nc, $preserveUserID = false) should be compatible with Concrete5_Model_Collection::duplicate()
Warning: Declaration of Concrete5_Model_CollectionAttributeKey::getList() should be compatible with Concrete5_Model_AttributeKey::getList($akCategoryHandle, $filters = Array)
Warning: Declaration of Concrete5_Model_CollectionAttributeKey::add($at, $args, $pkg = false) should be compatible with Concrete5_Model_AttributeKey::add($akCategoryHandle, $type, $args, $pkg = false)
```

We could use dynamic arguments and then check which one have a value and do the magic. Super ugly.. We could remove some of the methods in the parent class or rename them, but that will most likely break a few things.

If anyone has a better suggestion, please let me know!

**Comment by Remo** [comment]
This page `/dashboard/pages/attributes/edit/1/` seems to have a problem with the new include method:

```
`Warning: include(C:\Work\concrete5-legacy\web\concrete/attribute/type_form_header.php): failed to open stream: No such file or directory in C:\Work\concrete5-legacy\web\concrete\core\libraries\attribute\view.php on line 145` 
```

**Comment by mlocati** [comment]
Well, I guess we'd need to do for 5.6 all the LSP fixes we've done for 5.7...

**Comment by pekkanikolaus** [comment]
Is there a chance this is going to see any progress in the foreseeable future? I'd love to put in the work myself, but can't at the moment....

**Comment by mlocati** [comment]
@pekkanikolaus I don't think anyone will spendo so much time on the legacy version of concrete5. BTW @Remo expressed some interest in this

**Comment by Remo** [comment]
@pekkanikolaus I tried to find some people who are willing to write code or spend money to make this happen. So far I only found one customer who would pay a small amount of money, but by far not enough. Maybe things will start to change once php 5.6 is getting closer to EOL, but till then I don't think it's going to happen.

**Comment by pekkanikolaus** [comment]
@mlocati @Remo yeah, I totally understand. I would like to do a major site relaunch and use 5.6.3.4 for it ([here](https://www.concrete5.org/community/forums/5-7-discussion/disappointed-about-5.75.8-is-it-worth-starting-a-major-new-proje/) is some background discussion). They still support PHP 5.6 and it'll be a while until they don't, but I want this thing to be as future-proof as possible. 

 I also thought of a bounty, although I would probably also not be able to get nearly enough money greenlighted by my bosses to make it happen. @Remo - do you have a rough idea of how much it would take? If you do, feel free to drop me an E-Mail. If we can't get it done right now, then maybe I'll trust there will be enough interest once PHP 5.6 reaches end of life and panic opens pursestrings :)

**Comment by danielgasser** [comment]
@Remo I'd be interested in helping make it work, cause I think it would still be less work than migrating sites (big ones) from c5 5.6.x to v8.x. Do you still have any interests in doing this?

**Comment by Remo** [comment]
@danielgasser yes, got some information I can't share here, I'll call you in ~10min okay?

**Comment by JeRoNZ** [comment]
I'd be interested in have 5.6 run on PHP7. I have quite a few sites that simply won't be upgraded, so I would be up for helping make it work.

**Comment by Remo** [comment]
@JeRoNZ if you create pull requests I'd be happy to look at them! The goal would be to show warnings again and fix the code where necessary. LSP changes should be made in accordance with 5.7 wherever possible, I'm pretty sure we'll have to rename some methods.

**Comment by pekkanikolaus** [comment]
FYI I started a forum discussion about this https://www.concrete5.org/community/forums/chat/anyone-else-prefer-5.6s-ui-over-5.7s-and-5.8s-does-5.6-have-a-fu

**Comment by Remo** [comment]
Closed in favour of https://github.com/concrete5/concrete5-legacy/pull/1955

**Pull request closed without merging**
