### PR TITLE
Expand short tags

### PR DESCRIPTION
**Pull request by mlocati**
What about getting rid of PHP short open tags `<?`?

I also expanded the short echo tags (`<?=` &rarr; `<?php echo `) because the minimum supported PHP version is 5.3.2 (where short echo tags may not be enabled),

### CODE REVIEW

**Comment by Remo** [comment]
I'll probably merge this, going to think about it. Might be nice to finally close the ancient stories about short tags once and for all.

**Comment by mlocati** [comment]
The main reason for this step is that I don't think that the core team will publish a new legacy version on concrete5.org, so people that needs concrete5 5.6.4+ at the moment have to:
1. download the repository from github
2. expand the PHP short open tags
3. build the javascript and css assets

This pull request solves 2.
I'm also going to submit a pull request that solves 3 (I'll add the assets to the repository: since there's not that much active development in the legacy version, I don't think that'd hurt).

**Comment by mlocati** [comment]
> @mlocati why is step 3 needed?

You are right! My memory starts throwing too many checksum errors :wink:

**Comment by Remo** [comment]
Did anyone verify if we actually have the processed JavaScripts in the repo? When I create a PR I usually don't commit them to avoid merge conflicts.

**Comment by mlocati** [comment]
> Did anyone verify if we actually have the processed JavaScripts in the repo?

Yes, we have all the CSS and JavaScript assets in the repo. I'm not 100% sure the built assets are in sync with the source assets... To be sure, I'd rebuild them...

**Pull request merged**
