### PR TITLE
use number field for number attribute

### PR DESCRIPTION
**Pull request by Remo**

### CODE REVIEW

**Comment by Remo** [comment]
Does anyone have an idea why this would cause a problem?

**Comment by mlocati** [comment]
I think it's harmless

**Comment by JohntheFish** [comment]
+1. Now we have widespread implementation of number in browsers, it makes sense to use it.

**Comment by Remo** [comment]
@JohntheFish it's not even a problem if the browser doesn't support it. According to the spec an unknown type value has to fall back to the default type which is what we currently have. Only case where it might hurt is if someone has `input[type=text]` in his code.

**Comment by Remo** [comment]
Andrew merged this for 5.7..

**Pull request merged**
