### PR TITLE
Fixes a bug where the popup menu from the file / image editor starts flashing

### PR DESCRIPTION
**Pull request by LaurenceMommers**
Fixes a bug where the popup menu from the file / image editor starts flashing if you change the file multiple times ( without reloading the page ).

This is because a click event will be added everytime a file is selected.

### CODE REVIEW

**Comment by Remo** [comment]
@LaurenceMommers I can't reproduce this, can you please tell me what steps I have to take to see the problem myself? I resized a picture about 5 times and always saw the same behaviour.

**Comment by KorvinSzanto** [comment]
I'm worried about wholesale unbinding all events on this object, this may effect packages heavily.

**Comment by LaurenceMommers** [comment]
@Remo See this video:
http://demo.laurencemommers.nl/file_menu_bug.mp4

@KorvinSzanto Packages should not bind to that click, they should use the "callback" function "ccm_triggerSelectFileComplete" instead.

But i'll wrap the code in the anonymous function in a named function and then unbind that specific function only. ( later this night ).

**Comment by KorvinSzanto** [comment]
Yeah keeping track and unbinding this event instead of unbinding all events would be good. People do quite a lot more with these file selectors than just catch the file selection so I wouldn't be surprised if many of them bind events to these elements.

**Comment by LaurenceMommers** [comment]
"later this night" came early today :)
I made the change and tested it.

**Comment by KorvinSzanto** [comment]
@LaurenceMommers Can you give this event binding a namespace and unbind only the namespace?

```javascript
obj.unbind('click.concrete');
obj.on('click.concrete', ...);
```

**Comment by LaurenceMommers** [comment]
Why would you do that? ( just for my understanding ).

From what i understand the current solution shouls only remove the
ccm_triggerMenu function from the click event and leave all other events
registered.
Op 2 nov. 2015 19:53 schreef "Korvin Szanto" <notifications@github.com>:

**Comment by LaurenceMommers** [comment]
Forgot about this pull request, removed the named function and added the namespaced event binding

**Pull request merged**
