### PR TITLE
update to adodb v5.21.0-dev

### PR DESCRIPTION
**Pull request by Remo**

### CODE REVIEW

**Comment by hissy** [comment]
@Remo Do you have a plan to merge this pull request? How about upgrading ADOdb 5.21.4?

**Comment by Remo** [comment]
@hissy I have no plans for 5.6 at all ;-) But if there's a demand we can merge this, I just wonder if it's tested enough. But maybe you have a project where you could merge this and test it for a bit? I think at this point I would rather not merge something than break something.

**Comment by Remo** [comment]
maybe we should also update to v5.21.4? 5.22.2 only works with PHP 7, that might be too much, what do you think?

**Comment by hissy** [comment]
@Remo thanks, got it.

**Comment by hissy** [comment]
Yeah, 5.22 is too much. I'd like to test with 5.21

**Comment by Remo** [comment]
If you can test 5.21.4 well, I would merge it.

**Comment by ConcreteOwl** [comment]
Just been testing various versions of adodb and can report that versions 5.21.4 and 5.22.2 causes missing content in the 5.6.4.0 site pages.
However the adodb-master downloaded from https://github.com/ADOdb/ADOdb runs without any errors or problems.

**Comment by Remo** [comment]
@ConcreteOwl thanks for testing. I didn't expect this, but I guess we have to be careful about adodb. Not sure I would like to use the master branch though. Maybe we have to check what is wrong and wait for the next release?

**Pull request closed without merging**
